<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.0.3 setup script
 * Date: Fri, 07 Nov 2014 19:51:08 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: fpdb.cnxknkx8yknx.us-west-2.rds.amazonaws.com [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'fpdb.cnxknkx8yknx.us-west-2.rds.amazonaws.com';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysql';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'tricha';
$cfg['Servers'][$i]['password'] = 'fp14db!To?';
$cfg['Servers'][$i]['only_db'] = array('FPDB');
$cfg['Servers'][$i]['pmadb'] = 'FPDB';
$cfg['Servers'][$i]['controluser'] = 'tricha';
$cfg['Servers'][$i]['controlpass'] = 'fp14db!To?';

/* End of servers configuration */

$cfg['blowfish_secret'] = '545d21d59ec440.16303950';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>