<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.0.3 setup script
 * Date: Fri, 07 Nov 2014 02:43:07 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: fpmysql [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'fpmysql';
$cfg['Servers'][$i]['host'] = 'fpdb.cnxknkx8yknx.us-west-2.rds.amazonaws.com';
$cfg['Servers'][$i]['port'] = 3306;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysql';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'tricha';
$cfg['Servers'][$i]['password'] = 'fp14db!To?';
$cfg['Servers'][$i]['only_db'] = array('FPDB');

/* End of servers configuration */

$cfg['blowfish_secret'] = '545c2518e72015.44905683';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>